<?php
$_l['tag_desc']='Таги к записям.';
$_l['tag_form']='Теги (через запятую):';
$_l['tag_help']='Информация';
$_l['tag_sett']='Настройка';
$_l['tag_helps']='<p>Плагин позволяет присвоить записи смысловые метки-маркеры (таги) для более удобной навигации по темам блога.</p><p align="center"><b>Дополнительные функции</b></p><p>Для расширения функциональных возможностей в страницах и блоках можно использовать функции.</p>
<ul><li><font color="blue">tag_list(\'<font color="green">&lt;a href=<font color="#B00000">%link%</font>&gt;<font color="#B00000">%tag%</font>&lt;/a&gt; (<font color="#B00000">%num%</font>)</font>\')</font><br />
<i>Выводит список тагов.</i><br /><font color="#B00000">%link%</font> - ссылка на таг;<br /><font color="#B00000">%tag%</font> - название тага;<br /> <font color="#B00000">%num%</font> - количество записей с этим тагом.<br /></li>
<li><font color="blue">tag_cloud()</font><br />
<i>Выводит облако тагов.</i><br /></li>
<li><font color="blue">posts_by_tag(\'<font color="green">новости</font>\', <font color="green">10</font>, <font color="green">0</font>)</font><br />

<i>Выводит список записей с определенным тагом.</i> <br /><font color="green">новости</font> - таг записей<br /><font color="green">10</font> - количество записей<br /><font color="green">0</font> - выводить/невыводить топики (при установленном плагине <b>Topics</b>, необязательный параметр)</li>
<li><font color="blue">top_tag_cloud(<font color="green">0.6</font>, <font color="green">10</font>)</font><br />
<i>Выводит облако самых частых тагов.</i><br /><font color="green">0.6</font> - коофициент увеличения, например, в блоке можно поставить поменьше, а при выводе на отдельной странице - побольше.<br /><font color="green">10</font> - колличесво тегов<br /></li></ul>';
$_l['tags_tr']='транслитерация тегов (безопасный русский)';
$_l['tags_send']=' Изменить / сохранить ';
?>
