<?php
// russian:русский //

$_l['more'] = 'Читать дальше';
$_l['cmnt'] = 'комментарии';
$_l['cmnto'] = 'комментарий';
$_l['commentadd'] = 'Добавить';
$_l['commentnick'] = 'Имя';

$_l['notitle'] = '- - - -';
$_l['calendar_empty'] = '<center><b>Записей нет</b></center>';
$_l['anonymous'] = 'Прохожий';

$_l['subscribe'] = '<center><b>Вы подписались на комментарии к записи.</b></center>';
$_l['unsubscribe'] = '<center><b>Вы отписались от комментариев к записи.</b></center>';

$_l['ncikden'] = '<b><div align="center">Вы не можете использовать имя автора.</div></b>';
$_l['cmnt_add'] = '<center><b>Комментарий добавлен!</b></center>';

$_l['action_den'] = '<center><b>Недостаточно прав (или опущен обязательный параметр).</b></center>';

$_l['cmnt_add'] = '<center><b>Комментарий добавлен!</b></center>';
$_l['cmnt_den'] = '<center><b>Комментирование запрещено!</b></center>';
$_l['cmnt_addhide'] = '<center><b>Комментарий добавлен и скрыт (виден только автору)!</b></center>';
$_l['cmnt_attach'] = 'прикрепить файл';
$_l['cmnt_privat'] = 'приватный комментарий';
$_l['cmnt_wrong_capcha'] = '<center><b>Проверьте правильность введенного кода!</b></center>';
$_l['cmnt_notxt'] =  '<center><b>Необходимо ввести текст!</b></center>';
$_l['cmnt_www'] =  '<center><b>Ошибка ввода своего url!</b></center>';
$_l['post_notxt'] =  '<center><b>Необходимо ввести текст или заголовок!</b></center>';
$_l['not_found'] = '<center><b>Такой страницы нет.</b></center>';
$_l['search_not_found'] = '<center><b>Ничего не найдено.</b></center>';



$_l['ppp_link_next'] = 'Раньше &raquo;';
$_l['ppp_link_prev'] = '&laquo; Позже';

// Админ-центр
$_l['admclogin'] = 'Вход';
$_l['admclogout'] = 'Выход';


// уведомления на мыло
$_l['link']='Ссылка';
$_l['unlink']='Отписаться';


//шаблон
$_l['redirect'] = '<center><b>Пожалуйста, подождите 4 сек.</b><br />[ <a href=%link%>не ждать</a> ]</center>';
?>
